// art/scene.mjs — a REAL three-point perspective camera, and the box-cluster
// scene drawn through it. No hand-placed lines anywhere: every edge is a
// projected 3D edge, so convergence is a consequence of the projection rather
// than something an illustrator aimed for and missed.
//
// Why this exists: the artwork it replaces was generated by an image model that
// drew the two horizon points, drew a third point below the frame, and then drew
// every vertical edge PARALLEL — so the third point was decoration. Noah:
// "It CANNOT draw in 3 point perspective."
//
// The geometry, briefly. Three mutually perpendicular world directions project
// to three vanishing points, and those three points are not free: the triangle
// they form has the camera's principal point at its ORTHOCENTRE, and the focal
// length follows from it as f² = -(A-P)·(B-P). If that comes out negative there
// is no real camera with those three vanishing points, and no amount of drawing
// care will make the picture consistent. For two points on a horizon a distance
// 2s apart and a third d below it, the condition reduces to d > s: the nadir
// must be FARTHER below the horizon than half the spread of the other two.
// cameraFrom() refuses the impossible case instead of drawing it.

const sub = (p, q) => ({ x: p.x - q.x, y: p.y - q.y });
const dot3 = (u, v) => u.x * v.x + u.y * v.y + u.z * v.z;
const norm3 = u => {
  const m = Math.hypot(u.x, u.y, u.z);
  return { x: u.x / m, y: u.y / m, z: u.z / m };
};

/**
 * Derive the camera three given vanishing points imply.
 * @param {{x,y}} A first vanishing point (a horizon point, by convention)
 * @param {{x,y}} B second vanishing point (the other horizon point)
 * @param {{x,y}} C third vanishing point (the nadir, below the horizon)
 * @returns {{P, f, eA, eB, eC, orthogonality}}
 * @throws if the three points admit no real camera
 */
export function cameraFrom(A, B, C) {
  // Orthocentre of ABC: the point P with (P-A)·(B-C) = 0 and (P-B)·(A-C) = 0.
  const a1 = B.x - C.x, b1 = B.y - C.y, c1 = A.x * (B.x - C.x) + A.y * (B.y - C.y);
  const a2 = A.x - C.x, b2 = A.y - C.y, c2 = B.x * (A.x - C.x) + B.y * (A.y - C.y);
  const det = a1 * b2 - a2 * b1;
  if (Math.abs(det) < 1e-9) throw new Error("vanishing points are collinear — no camera");
  const P = { x: (c1 * b2 - c2 * b1) / det, y: (a1 * c2 - a2 * c1) / det };

  const pa = sub(A, P), pb = sub(B, P), pc = sub(C, P);
  const f2 = -(pa.x * pb.x + pa.y * pb.y);
  if (f2 <= 0) {
    // The useful diagnostic is not "invalid" but WHICH WAY it is invalid, so the
    // caller knows whether to spread the horizon points or drop the nadir.
    const s = Math.hypot(B.x - A.x, B.y - A.y) / 2;
    const d = Math.hypot(C.x - (A.x + B.x) / 2, C.y - (A.y + B.y) / 2);
    throw new Error(
      `no real camera has these three vanishing points: the triangle is obtuse ` +
      `(f² = ${f2.toFixed(0)}). Half the horizon spread is s=${s.toFixed(0)}px and the ` +
      `third point is d=${d.toFixed(0)}px away; a three-point perspective needs d > s. ` +
      `Move the horizon points ${Math.ceil(s - d) + 8}px closer together, or the third ` +
      `point ${Math.ceil(s - d) + 8}px farther out.`
    );
  }
  const f = Math.sqrt(f2);

  const eA = norm3({ x: pa.x, y: pa.y, z: f });
  const eB = norm3({ x: pb.x, y: pb.y, z: f });
  const eC = norm3({ x: pc.x, y: pc.y, z: f });

  // Proof, not faith: if P or f were wrong these three would not be orthogonal,
  // and every "convergence" downstream would be a coincidence.
  const orthogonality = Math.max(
    Math.abs(dot3(eA, eB)), Math.abs(dot3(eA, eC)), Math.abs(dot3(eB, eC))
  );
  if (orthogonality > 1e-9) throw new Error(`basis not orthogonal (${orthogonality})`);

  return { P, f, eA, eB, eC, orthogonality };
}

/** Camera-space point -> screen point. */
export function project(cam, p) {
  if (p.z <= 1e-9) throw new Error("point is at or behind the camera plane");
  return { x: cam.P.x + cam.f * p.x / p.z, y: cam.P.y + cam.f * p.y / p.z };
}

/** The ray through a screen point, as a unit direction in camera space. */
export function unproject(cam, s) {
  return norm3({ x: s.x - cam.P.x, y: s.y - cam.P.y, z: cam.f });
}

/**
 * Place the scene's origin on the ray through `at`, scaled so one world unit is
 * about `unitPx` pixels across there. Everything else is built in units.
 */
export function originAt(cam, at, unitPx) {
  const dir = unproject(cam, at);
  const t = cam.f / unitPx;              // f/z = px per unit  =>  z = f/unitPx
  return { x: dir.x * t / dir.z, y: dir.y * t / dir.z, z: t };
}

/**
 * Trim a camera-space segment to the near plane z = zMin, or drop it entirely.
 * A three-point camera with its third point inside the frame is necessarily very
 * wide, so a ground grid of any useful extent runs past the camera plane on the
 * near side — where z goes to zero, the projection blows up, and a line drawn
 * through it flips to the wrong side of the picture. Clipping is what makes the
 * fan honest instead of hiding the problem behind a smaller grid.
 */
export function clipNear(p, q, zMin) {
  if (p.z >= zMin && q.z >= zMin) return [p, q];
  if (p.z < zMin && q.z < zMin) return null;
  const [inP, outP] = p.z >= zMin ? [p, q] : [q, p];
  const s = (inP.z - zMin) / (inP.z - outP.z);
  const cut = {
    x: inP.x + (outP.x - inP.x) * s,
    y: inP.y + (outP.y - inP.y) * s,
    z: zMin,
  };
  return p.z >= zMin ? [inP, cut] : [cut, inP];
}

/** (a,b,c) in the camera's orthogonal frame -> camera-space point. */
export function at(cam, O, a, b, c) {
  return {
    x: O.x + a * cam.eA.x + b * cam.eB.x + c * cam.eC.x,
    y: O.y + a * cam.eA.y + b * cam.eB.y + c * cam.eC.y,
    z: O.z + a * cam.eA.z + b * cam.eB.z + c * cam.eC.z,
  };
}

/**
 * Perpendicular distance from a vanishing point to the infinite line through a
 * drawn segment. This is the whole claim of the picture, reduced to one number:
 * zero means that edge really does run to that point.
 */
export function missDistance(vp, p, q) {
  const dx = q.x - p.x, dy = q.y - p.y;
  const len = Math.hypot(dx, dy);
  if (len < 1e-12) return Infinity;
  return Math.abs(dy * (vp.x - p.x) - dx * (vp.y - p.y)) / len;
}

/** Signed angle of a segment, degrees, folded to [0,180) — for spread reports. */
export function angleOf(p, q) {
  const a = Math.atan2(q.y - p.y, q.x - p.x) * 180 / Math.PI;
  return ((a % 180) + 180) % 180;
}

// ---------------------------------------------------------------------------
// The scene: a cluster of boxes standing on the plane c = 0.
// Footprints are [a0,a1] x [b0,b1]; `h` is height, upward being -eC (because
// +eC points at the nadir, i.e. down-and-away from the camera).

// `h` is a FRACTION of the camera's own height above the ground plane, and it is
// ALLOWED TO EXCEED 1. Capping it below 1 cost a whole round: it was capped so no
// top face could ever be hidden, which produced squat slabs in a frame full of
// dead space. Noah: "Make them look long like skyscrapers as the example ... You
// aren't considering WHAT you are perspectiving."
//
// The geometry agrees with him. A point at exactly camera height projects ON the
// horizon; higher than that projects above it, and its top face turns away. So a
// tower taller than the camera SHOULD cross the horizon and show no roof — that is
// not a rendering fault, it is what a city looks like from up among the towers.
// The reference sketch has exactly this: one slab crossing the horizon with no
// roof, shorter blocks around it showing theirs.
//
// Footprints are small and heights large, because slenderness is what reads as
// "skyscraper": 0.52 units square at 1.38x a camera height of ~1.7 units puts the
// tall one near 4.5 times its own width.
export const CLUSTER = [
  { a: [0.00, 0.52], b: [0.00, 0.52], h: 1.38 },     // crosses the horizon, no roof
  { a: [-0.62, -0.08], b: [0.10, 0.66], h: 1.06 },   // tops out about at eye level
  { a: [0.62, 1.16], b: [-0.10, 0.44], h: 0.82 },
  { a: [0.06, 0.60], b: [-0.66, -0.10], h: 0.60 },
  { a: [-0.70, -0.14], b: [-0.60, -0.02], h: 0.34 },
  { a: [0.70, 1.22], b: [0.54, 1.10], h: 0.46 },
  { a: [-0.56, 0.06], b: [0.76, 1.30], h: 0.22 },
  { a: [1.28, 1.80], b: [-0.62, 0.02], h: 0.28 },
];

// A simpler silhouette for the icon. Below about 80px the rays and the grid are
// gone whatever their weight, so what survives is the outline of the group — and
// six boxes at that size is mush. Four, with one clearly tallest, still reads.
export const TIGHT_CLUSTER = [
  { a: [0.00, 0.54], b: [0.00, 0.54], h: 1.42 },
  { a: [-0.66, -0.06], b: [0.08, 0.70], h: 1.02 },
  { a: [0.64, 1.20], b: [-0.12, 0.46], h: 0.78 },
  { a: [0.04, 0.60], b: [-0.70, -0.08], h: 0.52 },
];

/**
 * A city block layout: towers set inside blocks, with streets between them.
 * `heights` is keyed "i,j" in camera-height fractions; a missing or zero entry is
 * an empty lot, which the eye needs — a fully built grid reads as one solid mass.
 * Returns the boxes AND the kerb lines, because the streets are the same lines the
 * blocks are laid out on rather than decoration drawn on afterwards.
 */
export function city({ module: m = 1.05, block = 0.67, i: iRange = [-1, 2], j: jRange = [-1, 1], heights = {}, pad = {} }) {
  const boxes = [], kerbs = [];
  const inset = (m - block) / 2;      // half a street each side, blocks centred
  for (let i = iRange[0]; i <= iRange[1]; i++) {
    for (let j = jRange[0]; j <= jRange[1]; j++) {
      const h = heights[`${i},${j}`] ?? 0;
      if (h <= 0) continue;
      boxes.push({ id: `${i},${j}`, a: [i * m + inset, i * m + inset + block], b: [j * m + inset, j * m + inset + block], h });
    }
  }
  // The streets may run FURTHER than the blocks do — usually toward the camera.
  // Towers placed that close are grotesque under a wide three-point camera (the
  // first attempt put two of them sprawling across the bottom of the frame), but
  // the roads sweeping down into the foreground are exactly what fills it.
  const span = {
    aLo: iRange[0] * m + (pad.aLo ?? 0), aHi: iRange[1] * m + m + (pad.aHi ?? 0),
    bLo: jRange[0] * m + (pad.bLo ?? 0), bHi: jRange[1] * m + m + (pad.bHi ?? 0),
  };
  for (let i = iRange[0]; i <= iRange[1] + 1; i++) {
    kerbs.push({ along: "b", at: i * m - inset }, { along: "b", at: i * m + inset + block });
  }
  for (let j = jRange[0]; j <= jRange[1] + 1; j++) {
    kerbs.push({ along: "a", at: j * m - inset }, { along: "a", at: j * m + inset + block });
  }
  return { boxes, kerbs, span };
}

const FACES = [
  // [normal axis, sign, four (a,b,c) corners in order]
  ["c", -1, box => [[box.a[0], box.b[0], -box.h], [box.a[1], box.b[0], -box.h], [box.a[1], box.b[1], -box.h], [box.a[0], box.b[1], -box.h]]], // top
  ["c", +1, box => [[box.a[0], box.b[0], 0], [box.a[1], box.b[0], 0], [box.a[1], box.b[1], 0], [box.a[0], box.b[1], 0]]],                     // bottom
  ["a", -1, box => [[box.a[0], box.b[0], 0], [box.a[0], box.b[1], 0], [box.a[0], box.b[1], -box.h], [box.a[0], box.b[0], -box.h]]],
  ["a", +1, box => [[box.a[1], box.b[0], 0], [box.a[1], box.b[1], 0], [box.a[1], box.b[1], -box.h], [box.a[1], box.b[0], -box.h]]],
  ["b", -1, box => [[box.a[0], box.b[0], 0], [box.a[1], box.b[0], 0], [box.a[1], box.b[0], -box.h], [box.a[0], box.b[0], -box.h]]],
  ["b", +1, box => [[box.a[0], box.b[1], 0], [box.a[1], box.b[1], 0], [box.a[1], box.b[1], -box.h], [box.a[0], box.b[1], -box.h]]],
];

/**
 * Build the drawable scene. Returns polygons and lines already in screen space,
 * each line tagged with the vanishing point it must run to, so the caller can
 * verify rather than assume.
 */
export function buildScene(cam, O, opts = {}) {
  const { A, B, C } = opts.vps;
  const gridA = opts.gridA ?? [-4, 5];
  const gridB = opts.gridB ?? [-4, 5];
  const p = (a, b, c) => project(cam, at(cam, O, a, b, c));
  const zMin = (opts.nearFrac ?? 0.3) * O.z;
  // How far the camera sits above the ground plane, in world units.
  const camHeight = dot3(O, cam.eC);
  const hScale = opts.hScale ?? 1;
  const cluster = (opts.cluster ?? CLUSTER).map(b => ({ ...b, h: b.h * hScale * camHeight }));

  const lines = [];   // {kind, vp, vpName, p, q, ...}
  const faces = [];   // {depth, pts, kind}

  // Ground grid — lines of constant b run along eA and must meet A; lines of
  // constant a run along eB and must meet B. Clipped to the near plane, and a
  // clipped segment still lies on the same line, so it still verifies.
  const gridLine = (p3, q3, vp, vpName) => {
    const seg = clipNear(p3, q3, zMin);
    if (!seg) return;
    lines.push({ kind: "grid", vp, vpName, p: project(cam, seg[0]), q: project(cam, seg[1]) });
  };
  // Roads first. A kerb running along b is a line of constant a, so it meets B —
  // tagged like every other line, and verified like every other line.
  if (opts.roads) {
    const { kerbs, span } = opts.roads;
    for (const k of kerbs) {
      const [p3, q3] = k.along === "b"
        ? [at(cam, O, k.at, span.bLo, 0), at(cam, O, k.at, span.bHi, 0)]
        : [at(cam, O, span.aLo, k.at, 0), at(cam, O, span.aHi, k.at, 0)];
      const seg = clipNear(p3, q3, zMin);
      if (!seg) continue;
      lines.push({
        kind: "road", vp: k.along === "b" ? B : A, vpName: k.along === "b" ? "B" : "A",
        p: project(cam, seg[0]), q: project(cam, seg[1]),
      });
    }
  }

  const step = opts.step ?? 1;
  for (let b = gridB[0]; b <= gridB[1] + 1e-9; b += step) {
    gridLine(at(cam, O, gridA[0], b, 0), at(cam, O, gridA[1], b, 0), A, "A");
  }
  for (let a = gridA[0]; a <= gridA[1] + 1e-9; a += step) {
    gridLine(at(cam, O, a, gridB[0], 0), at(cam, O, a, gridB[1], 0), B, "B");
  }

  // Guide rays. Each one is the supporting line of a real box edge, extended all
  // the way back to its vanishing point — which is what makes it a guide and not
  // a decoration: the ray and the edge are the same line.
  const over = opts.overshoot ?? 1.0;
  const past = (vp, q) => ({ x: vp.x + (q.x - vp.x) * over, y: vp.y + (q.y - vp.y) * over });
  for (const box of cluster) {
    for (const bb of [box.b[0], box.b[1]]) {
      lines.push({ kind: "guide", vp: A, vpName: "A", p: A, q: past(A, p(box.a[1], bb, -box.h)) });
    }
    for (const aa of [box.a[0], box.a[1]]) {
      lines.push({ kind: "guide", vp: B, vpName: "B", p: B, q: past(B, p(aa, box.b[1], -box.h)) });
    }
    // The third point. These are the ones the image model never drew: the
    // supporting lines of the VERTICAL edges, running down to the nadir.
    for (const aa of box.a) for (const bb of box.b) {
      lines.push({ kind: "nadir", vp: C, vpName: "C", p: C, q: past(C, p(aa, bb, -box.h)) });
    }
  }

  // Boxes: visible faces only. A face is visible when its outward normal points
  // back toward the camera — dot(normal, any point on the face) < 0.
  const axis = { a: cam.eA, b: cam.eB, c: cam.eC };
  for (const box of cluster) {
    // Nearest corner of the whole box orders it against the other boxes.
    let boxNear = Infinity;
    for (const aa of box.a) for (const bb of box.b) for (const cc of [0, -box.h]) {
      boxNear = Math.min(boxNear, at(cam, O, aa, bb, cc).z);
    }
    for (const [ax, sign, corners] of FACES) {
      const n = axis[ax], s = sign;
      const pts3 = corners(box).map(([a, b, c]) => at(cam, O, a, b, c));
      const mid = pts3.reduce((m, q) => ({ x: m.x + q.x / 4, y: m.y + q.y / 4, z: m.z + q.z / 4 }), { x: 0, y: 0, z: 0 });
      if (s * dot3(n, mid) >= 0) continue;                 // facing away
      faces.push({
        id: box.id,
        depth: boxNear,
        pts: pts3.map(q => project(cam, q)),
        edges: pts3.map((q, i) => [q, pts3[(i + 1) % 4]]),
      });
    }
    // The box's own edges, tagged, for verification and for stroking.
    const c0 = 0, c1 = -box.h;
    for (const bb of box.b) for (const cc of [c0, c1]) {
      lines.push({ kind: "edge", vp: A, vpName: "A", p: p(box.a[0], bb, cc), q: p(box.a[1], bb, cc) });
    }
    for (const aa of box.a) for (const cc of [c0, c1]) {
      lines.push({ kind: "edge", vp: B, vpName: "B", p: p(aa, box.b[0], cc), q: p(aa, box.b[1], cc) });
    }
    for (const aa of box.a) for (const bb of box.b) {
      lines.push({ kind: "edge", vp: C, vpName: "C", p: p(aa, bb, c0), q: p(aa, bb, c1) });
    }
  }

  faces.sort((u, v) => v.depth - u.depth);                 // far first

  // Is the third vanishing point hidden behind a building? The whole point of the
  // picture is that all three points are visible, and which lot covers it is not
  // something to squint at — it is a point-in-polygon test against the projected
  // faces, reported by lot id so the layout can be changed by name.
  const inside = (pt, poly) => {
    let hit = false;
    for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
      const a = poly[i], b = poly[j];
      if ((a.y > pt.y) !== (b.y > pt.y) &&
          pt.x < a.x + (b.x - a.x) * (pt.y - a.y) / (b.y - a.y)) hit = !hit;
    }
    return hit;
  };
  const covering = [...new Set(faces.filter(f => inside(C, f.pts)).map(f => f.id ?? "?"))];

  // Where the tallest tower's top actually lands. Composition is tuned against
  // this number, not against an impression: above the horizon by a little reads
  // as "taller than the camera"; off the top of the frame reads as a mistake.
  const tallest = cluster.reduce((m, b) => (b.h > m.h ? b : m), cluster[0]);
  const topY = Math.min(...tallest.a.flatMap(aa => tallest.b.map(bb => p(aa, bb, -tallest.h).y)));
  const baseY = Math.max(...tallest.a.flatMap(aa => tallest.b.map(bb => p(aa, bb, 0).y)));
  return { lines, faces, camHeight, zMin, topY, baseY, covering };
}

/**
 * Check every tagged line against the point it claims. Returns the worst miss
 * per vanishing point, and the angular SPREAD of each family — the spread is the
 * separate half of the claim: lines can all miss a point by zero and still be
 * parallel to each other, which is exactly the bug being fixed here.
 */
export function verify(scene) {
  const out = {};
  for (const name of ["A", "B", "C"]) {
    const fam = scene.lines.filter(l => l.vpName === name);
    let worst = 0, worstKind = null;
    let lo = Infinity, hi = -Infinity;
    for (const l of fam) {
      const m = missDistance(l.vp, l.p, l.q);
      if (m > worst) { worst = m; worstKind = l.kind; }
      const ang = angleOf(l.p, l.q);
      lo = Math.min(lo, ang); hi = Math.max(hi, ang);
    }
    out[name] = { count: fam.length, worstMiss: worst, worstKind, spreadDeg: hi - lo };
  }
  return out;
}
